# -*- coding: utf-8 -*-
"""Sprint_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yH2o9pxFr6kIJNO3KOGt1uPVM8JY2PVB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/dataset_custos_transporte_pas_ibge.csv')

df.head()

# Histograma
df["total_de_custos_mil_reais"].plot.hist(bins=32, color="blue", alpha=0.5);

plt.xlabel("Total de custos (mil reais)")
plt.ylabel("Frequência")
plt.title("Distribuição do Total de Custos")

plt.show()

# Gráfico de dispersão
plt.subplots(figsize=(10,6))

plt.yscale("log")

sct_plot = sns.scatterplot(
    x=df["combustiveis_lubrificantes_mil_reais"],
    y=df["total_de_custos_mil_reais"],
    hue=df["atividade"]
)

sct_plot.set_xlabel(
    "Combustíveis e lubrificantes (mil reais)",
    fontsize=12
)

sct_plot.set_ylabel(
    "Total de custos (mil reais)",
    fontsize=12
)

plt.show()

# Boxplot
ax = df.boxplot(
    column="total_de_custos_mil_reais",
    by="atividade",
    figsize=(15,6)
)

ax.set(
    xlabel="",
    ylabel="Total de custos (mil reais)"
)

plt.title("Total de Custos por Atividade")

plt.suptitle("")

plt.xticks(rotation=45)

plt.show()

# Heatmap

df_ = df[
    [
        "total_de_custos_mil_reais",
        "mercadorias_consumo_reposicao_mil_reais",
        "custo_mercadorias_revendidas_mil_reais",
        "combustiveis_lubrificantes_mil_reais",
        "outros_custos_mil_reais"
    ]
]

plt.subplots(figsize=(10,6))

sns.heatmap(
    df_.corr(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.xticks(rotation=45)
plt.title("Matriz de Correlação dos Custos")

plt.show()

